### ISSUE TITLE
Long tube names break column alignment

### ISSUE THREAD

**Issue by eltone** [kadekcipta/beanwalker#2]
Tube names longer than the "name" column width break alignment on all columns.

**Comment by mikegleasonjr** [comment]
:+1:

**Comment by kadekcipta** [comment]
For the moment I can only truncate  (with ellipsis) the long tube name to fit the column width and the original tube name (non-truncated) will be overlayed at the bottom border of the list view.
And also "name" column width has been made a little bit longer (25),  about 1/8 of max tube name length (200 from specs).

Please try the attached latest releases or build from the latest codes

**Comment by eltone** [comment]
Looks good to me. Thanks!
